-- SQL Schema to initialize SkillSync AI tables in Supabase SQL Editor

-- 1. Create Users Table
CREATE TABLE IF NOT EXISTS public.users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    full_name TEXT NOT NULL,
    email TEXT UNIQUE NOT NULL,
    password_hash TEXT NOT NULL
);

-- 2. Create Resumes Table
CREATE TABLE IF NOT EXISTS public.resumes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    user_id BIGINT NOT NULL, -- Keep loose reference or use REFERENCES public.users(id) ON DELETE CASCADE
    resume_text TEXT NOT NULL
);

-- 3. Create Analysis Results Table
CREATE TABLE IF NOT EXISTS public.analysis_results (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    resume_id BIGINT REFERENCES public.resumes(id) ON DELETE CASCADE,
    suggested_path TEXT NOT NULL,
    pros TEXT NOT NULL,
    cons TEXT NOT NULL
);

-- Enable Row Level Security (RLS) or disable as needed for direct REST access
-- Note: If you have active RLS, you must define appropriate policies for Select/Insert.
-- To allow the anonymous API key to read and write easily during dev testing, you can disable RLS:
ALTER TABLE public.users DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.resumes DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.analysis_results DISABLE ROW LEVEL SECURITY;
